"""Remove current_purse column

Revision ID: b4f81d233984
Revises: 007dfe3d764a
Create Date: 2025-03-16 01:13:29.369479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f81d233984'
down_revision: Union[str, None] = '007dfe3d764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'current_purse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('current_purse', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
